/** A single parsed line from an Elite Dangerous journal file. */
export interface JournalEvent {
  timestamp: string;
  event: string;
  [key: string]: unknown;
}

/** An event flowing through the pipeline, with provenance. */
export interface PipelineEvent {
  event: JournalEvent;
  /** True when the event came from replaying an existing journal on startup.
   *  Replayed events update state but never fire alerts. */
  replay: boolean;
  /** True when the event was generated by this app (Status.json transitions, simulator). */
  synthetic: boolean;
}

/** Parsed contents of Status.json. */
export interface ShipStatus {
  timestamp: string;
  event: string;
  Flags: number;
  Flags2?: number;
  Pips?: number[];
  FireGroup?: number;
  GuiFocus?: number;
  Fuel?: { FuelMain: number; FuelReservoir: number };
  Cargo?: number;
  LegalState?: string;
  Balance?: number;
  [key: string]: unknown;
}

export interface SessionStats {
  sessionStart: string;
  cmdr: string | null;
  ship: string | null;
  shipName: string | null;
  currentSystem: string | null;
  currentStation: string | null;
  docked: boolean;
  jumps: number;
  distanceLy: number;
  creditsEarned: number;
  bounties: number;
  bountyEarnings: number;
  missionsCompleted: number;
  deaths: number;
  interdictions: number;
  bodiesScanned: number;
  firstDiscoveries: number;
  fuelLevel: number | null;
  balance: number | null;
}

export interface RuleDefinition {
  name: string;
  enabled?: boolean;
  /** Journal event name(s) to match, or "*" for all events. */
  trigger: string | string[];
  /** Optional JS expression over `event`, `status`, `session`. */
  when?: string;
  /** Minimum seconds between firings of this rule. */
  cooldown?: number;
  /** Streamer.bot action name to invoke. */
  action: string;
  /** Argument templates passed to the action ({{path | filter}} syntax). */
  args?: Record<string, string>;
  /** Fire on replayed events too (default false; almost never what you want). */
  fireOnReplay?: boolean;
  /**
   * Allow full JavaScript in `when` (runs with new Function). Off by default:
   * shared rule files should not be able to execute arbitrary code. Only set
   * this on rules you wrote yourself.
   */
  unsafe?: boolean;
}

export interface LoadedRule extends RuleDefinition {
  /** Source file the rule came from. */
  file: string;
  /** Compiled `when` predicate. */
  predicate: ((event: JournalEvent, status: ShipStatus | null, session: SessionStats) => boolean) | null;
  lastFired: number | null;
  fireCount: number;
  /** How many live events matched this rule's trigger (condition or not). */
  seenCount: number;
  /** Set when the rule file failed to compile; rule is skipped. */
  error: string | null;
}

export interface DispatchRecord {
  timestamp: string;
  rule: string;
  action: string;
  args: Record<string, string>;
  /** "sent" = delivered, "queued" = buffered while disconnected,
   *  "error" = Streamer.bot rejected it (usually: no action with that name). */
  status: 'sent' | 'queued' | 'error';
  /** WebSocket request id, used to correlate Streamer.bot's response. */
  id?: string;
  /** Error detail when status is "error". */
  error?: string;
}
